import pygame

pygame.init()
again = pygame.image.load('images/again.png')
bomb = pygame.image.load('images/bomb.png')
bomb_supply = pygame.image.load('images/bomb_supply.png')
bullet_supply = pygame.image.load('images/bullet_supply.png')
bullet1 = pygame.image.load('images/bullet1.png')
bullet2 = pygame.image.load('images/bullet2.png')
bullet3 = pygame.image.load('images/bullet3.png')
bullet4 = pygame.image.load('images/bullet4.png')
bullet5 = pygame.image.load('images/bullet5.png')
enemy1 = pygame.image.load('images/enemy1.png')
enemy1_down1 = pygame.image.load('images/enemy1_down1.png')
enemy1_down2 = pygame.image.load('images/enemy1_down2.png')
enemy1_down3 = pygame.image.load('images/enemy1_down3.png')
enemy1_down4 = pygame.image.load('images/enemy1_down4.png')
enemy2 = pygame.image.load('images/enemy2.png')
enemy2_down1 = pygame.image.load('images/enemy2_down1.png')
enemy2_down2 = pygame.image.load('images/enemy2_down2.png')
enemy2_down3 = pygame.image.load('images/enemy2_down3.png')
enemy2_down4 = pygame.image.load('images/enemy2_down4.png')
enemy2_hit = pygame.image.load('images/enemy2_hit.png')
enemy3_down1 = pygame.image.load('images/enemy3_down1.png')
enemy3_down2 = pygame.image.load('images/enemy3_down2.png')
enemy3_down3 = pygame.image.load('images/enemy3_down3.png')
enemy3_down4 = pygame.image.load('images/enemy3_down4.png')
enemy3_down5 = pygame.image.load('images/enemy3_down5.png')
enemy3_down6 = pygame.image.load('images/enemy3_down6.png')
enemy3_hit = pygame.image.load('images/enemy3_hit.png')
enemy3_n1 = pygame.image.load('images/enemy3_n1.png')
enemy3_n2 = pygame.image.load('images/enemy3_n2.png')
feidan = pygame.image.load('images/feidan.png')
gameover = pygame.image.load('images/gameover.png')
life = pygame.image.load('images/life.png')
life1 = pygame.image.load('images/life1.png')
me_destroy_1 = pygame.image.load('images/me_destroy_1.png')
me_destroy_2 = pygame.image.load('images/me_destroy_2.png')
me_destroy_3 = pygame.image.load('images/me_destroy_3.png')
me_destroy_4 = pygame.image.load('images/me_destroy_4.png')
me1 = pygame.image.load('images/me1.png')
me2 = pygame.image.load('images/me2.png')
pause_nor = pygame.image.load('images/pause_nor.png')
pause_pressed = pygame.image.load('images/pause_pressed.png')
resume_nor = pygame.image.load('images/resume_nor.png')
resume_pressed = pygame.image.load('images/resume_pressed.png')
shield01 = pygame.image.load('images/shield01.png')
shield02 = pygame.image.load('images/shield02.png')

pygame.quit()